version: "3.9"

services:
  app:
    build: .
    env_file: .env
    command: bash -c "alembic upgrade head || true; uvicorn app.web.oauth_server:app --host 0.0.0.0 --port 8000 & python -m app.bot.main"
    ports:
      - "8000:8000"